# Generated by Django 6.0.5 on 2026-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
