# Generated by Django 6.0.5 on 2026-05-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='title',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
