# Generated by Django 6.0.5 on 2026-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='title',
        ),
    ]
